branches:
  only:
    - master

services:
    - docker

before_install:
    - docker --version

script:
    - IMAGE="polinux/cerebro"
    - docker build -t "$IMAGE" .

    - docker run -d --name cerebro -p 9000:9000 "$IMAGE"
    # TEST
    - while true; do if grep "Listening for HTTP on /0.0.0.0:9000" | docker logs cerebro; then break; else sleep 1; fi done
    - curl -sSLi http://localhost:9000 | grep '200 OK' 